#!/bin/bash -e

USER_ID=${SUDO_UID:-$(id -u)}
HOME=$(getent passwd "${USER_ID}" | cut -d: -f6)

if [[ -z "${SUDO_UID}" && "${USER_ID}" != "0" ]]; then
  echo "Script should be run using sudo"
  exit 1
fi

if [ ! -f ${HOME}/setup-network-environment ]; then
  # Remove unfinished file when you press Ctrl+C
  trap "rm -f ${HOME}/setup-network-environment" INT TERM
  wget --no-verbose https://github.com/kelseyhightower/setup-network-environment/releases/download/1.0.1/setup-network-environment -P ${HOME}
fi

if [ ! -x ${HOME}/setup-network-environment ]; then
  chmod +x ${HOME}/setup-network-environment
fi

${HOME}/setup-network-environment
source /etc/network-environment

DROPIN="[Service]
Environment='ETCD_ADVERTISE_CLIENT_URLS=http://${DEFAULT_IPV4}:2379'
Environment='ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379,http://0.0.0.0:4001'"

mkdir -p /etc/systemd/system/etcd2.service.d/
echo "${DROPIN}" > /etc/systemd/system/etcd2.service.d/90-run-local-member.conf
systemctl daemon-reload
systemctl start etcd2
