#!/bin/bash -e

CDIR=$(cd `dirname $0` && pwd)
USER_ID=${SUDO_UID:-$(id -u)}
HOME=$(getent passwd "${USER_ID}" | cut -d: -f6)

cd ${CDIR}/../
export VERSION=$(git describe --dirty)
export GOROOT=${HOME}/go
export PATH=${HOME}/go/bin:${PATH}

if [ ! -S "$SSH_AUTH_SOCK" ]; then
  eval $(ssh-agent)
fi

chmod 600 functional/fixtures/id_rsa
ssh-add functional/fixtures/id_rsa
sudo systemctl stop fleet || true

if [[ ! $(go version 2>/dev/null) ]]; then
  functional/provision/install_go.sh
fi

if [ ! -x "bin/fleetd" ] || \
   [ ! -x "bin/fleetctl" ] || \
   [ ! $(bin/fleetctl | grep "$VERSION") ]; then
  ./build
fi

source functional/test-env
eval $(go env)
go test github.com/coreos/fleet/functional -ldflags "${GLDFLAGS}" -v
